#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BACKPORT_BUILD_GENERIC_ATOMIC64 1
#define CPTCFG_BACKPORT_OPTION_BT_SOCK_CREATE_NEEDS_KERN 1
#define CPTCFG_BACKPORT_BUILD_DMA_SHARED_HELPERS 1
#define CPTCFG_SSB_POSSIBLE 1
#define CPTCFG_BCMA_POSSIBLE 1
#define CPTCFG_WIREGUARD_MODULE 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
