#!/bin/sh

[ -f /tmp/ethernet.state1 ] && rm /tmp/ethernet.state1
[ -f /tmp/ethernet.state2 ] && rm /tmp/ethernet.state2
[ -f /tmp/ethernet.state3 ] && rm /tmp/ethernet.state3

VWAN=$(nvram get wan_ifname)

VPORT=$(nvram get $VWAN'ports' | awk '{print $1}' | sed 's/[^0-9]*//g')
[ -z "$VPORT" ] && VPORT="0"

/usr/sbin/robocfg showports | grep Port | awk '{print $1" "$2" "$3}' > /tmp/ethernet.state.tmp

# Search WAN port
SWAN=$(cat /tmp/ethernet.state.tmp | grep "Port $VPORT" | awk '{print $3}')
echo "Port 0: $SWAN" > /tmp/ethernet.state
sed -n -e "/Port $VPORT:/!p" /tmp/ethernet.state.tmp > /tmp/ethernet.state1

[ "$(nvram get model)" == "R1D" ] && {
	sed -i '/Port 1/d' /tmp/ethernet.state1
	sed -i '/Port 3/d' /tmp/ethernet.state1
}

sed -i '/Port 5/d' /tmp/ethernet.state1
sed -i '/Port 7/d' /tmp/ethernet.state1
sed -i '/Port 8/d' /tmp/ethernet.state1

NUM="1"
REVERT=$(nvram get lan_invert)
[ "$REVERT" -eq 1 ] && {
	cat /tmp/ethernet.state1 | sort -r >> /tmp/ethernet.state2
	exec 0< /tmp/ethernet.state2
		while read line; test -n "$line"; do
			STATE=$(echo $line | awk '{print $3}')
			echo "Port $NUM: $STATE" >> /tmp/ethernet.state3
			NUM=$((NUM+1))
		done
} || {
	exec 0< /tmp/ethernet.state1
		while read line; test -n "$line"; do
			STATE=$(echo $line | awk '{print $3}')
			echo "Port $NUM: $STATE" >> /tmp/ethernet.state3
			NUM=$((NUM+1))
		done
}

cat /tmp/ethernet.state3 >> /tmp/ethernet.state

[ -f /tmp/ethernet.state1 ] && rm /tmp/ethernet.state1
[ -f /tmp/ethernet.state2 ] && rm /tmp/ethernet.state2
[ -f /tmp/ethernet.state3 ] && rm /tmp/ethernet.state3
