#!/bin/sh

# Script for checking/adding to cron MySQL

case "$1" in
	addcru)
		ISCRU=$(cru l | grep mysql_inside | wc -l)

		INTERVAL=$(nvram get mysql_check_time)

		BTON=$(nvram get mysql_enable)
		[ "$BTON" == "1" ] && {
			BTCH=$(nvram get mysql_check)
			[ "$BTCH" == "1" ] && {
				[ "$ISCRU" == "0" ] && {
					cru a mysql_inside "*/$INTERVAL * * * * /usr/bin/mycheck check"
				} || {
					cru d mysql_inside
					cru a mysql_inside "*/$INTERVAL * * * * /usr/bin/mycheck check"
				}
			} || {
				[ "$ISCRU" == "1" ] && cru d mysql_inside
			}
		} || {
			[ "$ISCRU" == "1" ] && cru d mysql_inside
		}
	;;
	check)
		BTON=$(nvram get mysql_enable)
		[ "$BTON" == "1" ] && {
			BTCH=$(nvram get mysql_check)
			[ "$BTCH" == "1" ] && {
				ON=$(ps w | grep mysqld | grep -v grep | wc -l)
				[ "$ON" == "0" ] && {
					logger MySQL stopped? Starting...
					service mysql restart
				}
			}
		}
	;;
esac
exit 0
