#!/bin/sh

#
# Shibby 2013
# Fix memory leak + cosmetics - pedro 2019
#

[ ! "$(nvram get web_css)" == "online" ] && exit 0

PID=$$
LOCK="/tmp/ttb.lock"
DIR="/www/ext"
LOGS="logger -t TTB[$PID]"

# script in action
[ -f $LOCK ] && {
	$LOGS "Another process in action - exiting"
	exit 0
} || {
	touch $LOCK
	TTB=$(nvram get ttb_css)

	# no skin
	[ ! -f $DIR/$TTB.css ] && {
		# no skin but zip with skin is available
		[ -f $DIR/$TTB.zip ] && {
			unzip -o $DIR/$TTB.zip -d $DIR/
			$LOGS "Online theme ($TTB) has been applied"
			cru d ttbDL
		# no skin either zip
		} || {
			rm $DIR/*.css $DIR/*.zip $DIR/*.png $DIR/*.gif $DIR/*.jpg
			wget -T 10 -t 1 http://www.tomatothemebase.eu/wp-content/uploads/$TTB.zip -O $DIR/$TTB.zip
			sleep 1

			# zip downloaded
			[ -f $DIR/$TTB.zip ] && {
				unzip -o $DIR/$TTB.zip -d $DIR/
				$LOGS "Online theme ($TTB) has been downloaded and applied"
				cru d ttbDL
			# can't download zip!!
			} || {
				$LOGS "Cannot download Online theme. Will try again soon ..."
				cru a ttbDL "* * * * * /usr/sbin/ttb"
			}
		}
	}

	rm $LOCK
}
