#!/bin/sh

# Shibby 2013

[ ! "$(nvram get web_css)" == "online" ] && {
	exit 0
}

LOCK="/tmp/ttb.lock"

# script in action
[ -f $LOCK ] && {
	logger TTB: Another process is already working. Exiting...
	exit 0
} || {
	touch $LOCK
	TTB=$(nvram get ttb_css)

	# no skin
	[ ! -f /www/ext/$TTB.css ] && {
		# no skin but zip with skin is available
		[ -f /www/ext/$TTB.zip ] && {
			unzip -o /www/ext/$TTB.zip -d /www/ext/
		# no skin either zip
		} || {
			rm /www/ext/*.css /www/ext/*.zip /www/ext/*.png /www/ext/*.gif /www/ext/*.jpg
			wget http://www.tomatothemebase.eu/wp-content/uploads/$TTB.zip -O /www/ext/$TTB.zip
			sleep 5

			# zip downloaded
			[ -f /www/ext/$TTB.zip ] && {
				unzip -o /www/ext/$TTB.zip -d /www/ext/
			# can't download zip!!
			} || {
				logger TTB: Cannot download Online themes. Will try again soon...
				sleep 30
				rm $LOCK
				/usr/sbin/ttb
			}
		}
	}

	rm $LOCK
}
